services:
  build-image:
    image: atmega-tdd
    command: bash -c "echo build-image completed."
    build: .
  build-hex:
    image: atmega-tdd
    command: bash -c "mkdir -p Build && cd Build && cmake .. && cmake --build ."
    depends_on:
    - build-image
    volumes:
    - ./:/app
  static-analysis:
    image: atmega-tdd
    command: bash -c "mkdir -p Build && cd Build && cmake .. && \
                      cmake --build . && cd .. && chmod +x clang-tidy.sh && \
                      ./clang-tidy.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  unit-tests:
    image: atmega-tdd
    command: bash -c "cd Tests && ceedling version && ceedling clobber && \
                      ceedling test:all"
    depends_on:
    - build-image
    volumes:
    - ./:/app
