name: main-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run image
        run:  docker compose run build-test
  unit-tests:
    runs-on: ubuntu-latest
    needs: build-test # project has to build successfully before unit tests
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run image
        run:  docker compose run unit-tests
