name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build-hex:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: build hex file
        run:  docker compose run --rm build-hex
      - name: upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hex-file
          path: Build/main.hex
  unit-tests:
    runs-on: ubuntu-latest
    needs: build-hex # project has to build successfully before unit tests
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run unit tests
        run:  docker compose run --rm unit-tests
